const genresAll = [
  "Klasik",
  "Bilim Kurgu",
  "Polisiye",
  "Korku",
  "Macera",
  "Fantastik",
  "Biyografi",
  "Tarih",
  "Romantik",
  "Drama",
  "Komedi",
  "Gerilim",
  "Mistik",
  "Felsefi",
  "Aksiyon",
  "Çocuk Kitabı",
  "Genç Yetişkin",
  "Bilim",
  "Uyarlama",
  "Edebiyat Eleştirisi",
  "Kurgusal Olmayan",
  "Kısa Hikaye",
  "Şiir",
  "Oyun",
  "Yemek Kitabı",
  "Seyahat",
  "Rehber",
  "Sanat",
  "Fotoğrafçılık",
  "Moda",
  "Müzik",
  "Spor",
  "Doğa",
  "Teknoloji",
  "Bilgisayar Bilimi",
  "Sosyoloji",
  "Psikoloji",
  "Eğitim",
  "İş ve Kariyer",
  "Kişisel Gelişim",
  "Sağlık ve Fitness",
  "Meditasyon",
  "Din ve Spiritüalizm",
  "Felsefe",
  "Yoga",
  "Hayvanlar",
  "Çevre",
  "Politika",
  "Ekonomi",
  "Mitoloji",
  "Kültür",
  "Diyalog",
  "Tiyatro",
  "Müzikal",
  "Opera",
  "Bale",
  "Resim",
  "Heykel",
  "Grafik Tasarım",
  "Animasyon",
  "Belgesel",
  "Bilim Tarihi",
  "Mühendislik",
  "Matematik",
  "Astronomi",
  "Uzay",
  "Astrofizik",
  "Jeoloji",
  "Coğrafya",
  "Meteoroloji",
  "Ekoloji",
  "Zooloji",
  "Botanik",
  "Antropoloji",
  "Arkeoloji",
  "Mimarlık",
  "İç Mimarlık",
  "Peyzaj Mimarlığı",
  "Siyaset Bilimi",
  "Uluslararası İlişkiler",
  "Hukuk",
  "Eticaret",
  "Pazarlama",
  "Marka Yönetimi",
  "Reklamcılık",
  "Perakende",
  "E-ticaret",
  "Finans",
  "Muhasebe",
  "Sigortacılık",
  "Ticaret",
  "Yatırım",
  "Bankacılık",
  "Mikroekonomi",
  "Makroekonomi",
  "Uluslararası Ekonomi",
  "Turizm",
  "Otelcilik",
  "Restoran Yönetimi",
];

export default genresAll;
